timeout: '10m'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/settings-maven-central-publish/versions/latest
      env: 'MAVEN_SETTINGS'
    - versionName: projects/$PROJECT_ID/secrets/credentials-maven-central-username/versions/latest
      env: 'OSSRH_USERNAME'
    - versionName: projects/$PROJECT_ID/secrets/credentials-maven-central-password/versions/latest
      env: 'OSSRH_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/credentials-maven-central-private-key/versions/latest
      env: 'ORG_GRADLE_PROJECT_signingKey'
    - versionName: projects/$PROJECT_ID/secrets/credentials-maven-central-signing-keyid/versions/latest
      env: 'ORG_GRADLE_PROJECT_signingKeyId'
    - versionName: projects/$PROJECT_ID/secrets/credentials-maven-central-signing-password/versions/latest
      env: 'ORG_GRADLE_PROJECT_signingPassword'

steps:
  - id: 'fetch-tags'
    name: 'gcr.io/cloud-builders/git'
    args: [ fetch, --depth=100 ]

  - id: 'build'
    name: 'gcr.io/cloud-builders/javac'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export CURRENT_VERSION=$$(git describe --tags) && ./gradlew clean build

  - id: 'release'
    name: 'gcr.io/cloud-builders/javac'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $${MAVEN_SETTINGS} | base64 --decode > settings.xml
        export CURRENT_VERSION=$$(git describe --tags) && ./gradlew uploadArchives
    secretEnv: [
        'MAVEN_SETTINGS', 'OSSRH_USERNAME', 'OSSRH_PASSWORD',
        'ORG_GRADLE_PROJECT_signingKey',
        'ORG_GRADLE_PROJECT_signingKeyId',
        'ORG_GRADLE_PROJECT_signingPassword'
    ]
