timeout: '5m'

steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/javac'
    entrypoint: 'bash'
    env:
      - 'CURRENT_VERSION=${SHORT_SHA}'
    args:
      - '-c'
      - |
        ./gradlew clean build
