timeout: '5m'
options:
  dynamic_substitutions: true
substitutions:
  - _BASE_IMAGE_JAVA: gcr.io/cloud-builders/javac

steps:
  - id: 'build'
    name: ${_BASE_IMAGE_JAVA}
    entrypoint: 'bash'
    env:
      - 'CURRENT_VERSION=${SHORT_SHA}'
    args:
      - '-c'
      - |
        ./gradlew clean build
